import Foundation
import SwiftProtobuf
import CockpitTypes

public struct HostDataPlaneBinding: Hashable, Sendable {
    public let clientInstanceID: ClientInstanceID
    public let windowID: WindowID
    public let workspaceContextID: WorkspaceContextID
    public let environmentID: EnvironmentID
    public let activeContextGeneration: UInt64
    public init(validatingClientInstanceID clientInstanceID: ClientInstanceID, windowID: WindowID, workspaceContextID: WorkspaceContextID, environmentID: EnvironmentID, activeContextGeneration: UInt64) throws {
        guard activeContextGeneration > 0, activeContextGeneration <= documentJavaScriptMaximum else { throw ProtocolMappingError.invalidValue("host_data_plane_binding") }
        self.clientInstanceID = clientInstanceID; self.windowID = windowID; self.workspaceContextID = workspaceContextID; self.environmentID = environmentID; self.activeContextGeneration = activeContextGeneration
    }
}

public struct DataPlaneRemoteError: Error, Hashable, Sendable {
    public let code: CPDataPlaneErrorCode; public let expected: UInt64?; public let actual: UInt64?
    public init(validatingCode code: CPDataPlaneErrorCode, expected: UInt64?, actual: UInt64?) throws {
        let paired: Bool
        switch code { case .generationMismatch, .treeRevisionUnavailable: paired = true
        case .malformedMessage, .wrongChannel, .sequenceViolation, .ackViolation, .unauthorizedPeer, .invalidTicket, .ticketExpired, .ticketReplay, .contextMismatch, .environmentMismatch, .requestIDReuse, .treeZeroGeneration, .treeSymbolicLink, .treeEventSourceUnavailable, .treeEnumerationFailed, .treeBackpressure, .requestCancelled, .internal: paired = false
        default: throw ProtocolMappingError.invalidValue("data_plane_error") }
        guard (expected != nil) == paired, (actual != nil) == paired, expected.map({ $0 <= documentJavaScriptMaximum }) ?? true, actual.map({ $0 <= documentJavaScriptMaximum }) ?? true else { throw ProtocolMappingError.invalidValue("data_plane_error") }
        self.code = code; self.expected = expected; self.actual = actual
    }
}

public enum HostDataPlaneDecodedEnvelope: Sendable { case control(CPHostDataPlaneControlEnvelope); case document(CPDocumentEnvelope); case fileTree(CPFileTreeEnvelope) }

public enum HostDataPlaneMessages {
    public static func encode(_ value: HostDataPlaneBinding) throws -> CPDataPlaneBinding { var m = CPDataPlaneBinding(); m.clientInstanceID = value.clientInstanceID.description; m.windowID = value.windowID.description; m.workspaceContextID = context(value.workspaceContextID); m.environmentID = value.environmentID.description; m.activeContextGeneration = value.activeContextGeneration; return m }
    public static func decode(_ m: CPDataPlaneBinding) throws -> HostDataPlaneBinding { try unknown(m.unknownFields.data, "data_plane_binding"); guard m.hasWorkspaceContextID else { throw invalid("host_data_plane_binding") }; return try .init(validatingClientInstanceID: id(m.clientInstanceID, "client_instance_id"), windowID: id(m.windowID, "window_id"), workspaceContextID: try context(m.workspaceContextID), environmentID: id(m.environmentID, "environment_id"), activeContextGeneration: m.activeContextGeneration) }

    public static func encode(_ v: UTF16TextEdit) throws -> CPUTF16TextChange { var m = CPUTF16TextChange(); m.offset = v.offset; m.length = v.length; m.replacement = v.replacement; return m }
    public static func decode(_ m: CPUTF16TextChange) throws -> UTF16TextEdit { try unknown(m.unknownFields.data, "utf16_text_change"); do { return try .init(validatingOffset: m.offset, length: m.length, replacement: m.replacement) } catch { throw invalid("utf16_text_change") } }

    public static func encode(_ v: DiskFingerprint) throws -> CPDiskFingerprintValue { var m = CPDiskFingerprintValue(); m.deviceID = v.deviceID; m.inode = v.inode; m.byteCount = v.byteCount; m.modificationTimeSeconds = v.modificationTimeSeconds; m.modificationTimeNanoseconds = v.modificationTimeNanoseconds; m.contentSha256 = v.contentSHA256.bytes; return m }
    public static func decode(_ m: CPDiskFingerprintValue) throws -> DiskFingerprint { try unknown(m.unknownFields.data, "disk_fingerprint"); guard m.modificationTimeNanoseconds < 1_000_000_000, let d = try? SHA256Digest(validating: m.contentSha256) else { throw invalid("disk_fingerprint") }; return .init(deviceID: m.deviceID, inode: m.inode, byteCount: m.byteCount, modificationTimeSeconds: m.modificationTimeSeconds, modificationTimeNanoseconds: m.modificationTimeNanoseconds, contentSHA256: d) }

    public static func encode(_ v: EditLease) throws -> CPEditLeaseValue { var m = CPEditLeaseValue(); m.editLeaseID = v.id.description; m.documentID = v.documentID.description; m.clientInstanceID = v.clientInstanceID.description; return m }
    public static func decode(_ m: CPEditLeaseValue) throws -> EditLease { try unknown(m.unknownFields.data, "edit_lease"); do { return try .init(validatingID: id(m.editLeaseID, "edit_lease_id"), documentID: id(m.documentID, "document_id"), clientInstanceID: id(m.clientInstanceID, "client_instance_id")) } catch let e as ProtocolMappingError { throw e } catch { throw invalid("edit_lease") } }

    public static func encode(_ v: DocumentSnapshot) throws -> CPDocumentSnapshotValue { var m = CPDocumentSnapshotValue(); m.documentID = v.documentID.description; m.environmentID = v.environmentID.description; m.relativePath = v.relativePath.string; m.text = v.text; m.documentVersion = v.documentVersion; m.persistedVersion = v.persistedVersion; m.lastAcceptedClientSequence = v.lastAcceptedClientSequence; m.dirtyState = dirty(v.dirtyState); if let f = v.observedDiskFingerprint { m.observedDiskFingerprint = try encode(f) }; if let l = v.currentLease { m.currentLease = try encode(l) }; m.maintenance = v.maintenance.map { maintenance($0) }; return m }
    public static func decode(_ m: CPDocumentSnapshotValue) throws -> DocumentSnapshot { try unknown(m.unknownFields.data, "document_snapshot"); let did: DocumentID = try id(m.documentID, "document_id"); let eid: EnvironmentID = try id(m.environmentID, "environment_id"); guard let path = try? RelativePath(m.relativePath), let state = try? dirty(m.dirtyState), !m.text.contains("\r"), !m.text.contains("\0") else { throw invalid("document_snapshot") }; let fp = try m.hasObservedDiskFingerprint ? decode(m.observedDiskFingerprint) : nil; let lease = try m.hasCurrentLease ? decode(m.currentLease) : nil; guard lease?.documentID == did || lease == nil else { throw invalid("document_snapshot") }; do { return try .init(validatingDocumentID: did, environmentID: eid, relativePath: path, text: m.text, documentVersion: m.documentVersion, persistedVersion: m.persistedVersion, lastAcceptedClientSequence: m.lastAcceptedClientSequence, dirtyState: state, observedDiskFingerprint: fp, currentLease: lease, maintenance: try m.maintenance.map { try maintenance($0) }) } catch { throw invalid("document_snapshot") } }

    public static func encode(_ v: EditAcknowledgement) throws -> CPDocumentAcknowledgement { var m = CPDocumentAcknowledgement(); m.documentID = v.documentID.description; m.clientSequence = v.clientSequence; m.documentVersion = v.documentVersion; return m }
    public static func decode(_ m: CPDocumentAcknowledgement) throws -> EditAcknowledgement { try unknown(m.unknownFields.data, "document_acknowledgement"); do { return try .init(validatingDocumentID: id(m.documentID, "document_id"), clientSequence: m.clientSequence, documentVersion: m.documentVersion) } catch let e as ProtocolMappingError { throw e } catch { throw invalid("document_acknowledgement") } }
    public static func encode(_ v: EditTransaction) throws -> CPDocumentApplyRequest { var m = CPDocumentApplyRequest(); m.documentID = v.documentID.description; m.editLeaseID = v.editLeaseID.description; m.baseVersion = v.baseVersion; m.clientSequence = v.clientSequence; m.changes = try v.changes.map(encode); return m }
    public static func decode(_ m: CPDocumentApplyRequest) throws -> EditTransaction { try unknown(m.unknownFields.data, "document_apply_request"); do { return try .init(validatingDocumentID: id(m.documentID, "document_id"), editLeaseID: id(m.editLeaseID, "edit_lease_id"), baseVersion: m.baseVersion, clientSequence: m.clientSequence, changes: try m.changes.map(decode)) } catch let e as ProtocolMappingError { throw e } catch { throw invalid("document_apply_request") } }

    public static func encode(_ v: WorkspaceDirectory) throws -> CPWorkspaceDirectoryValue { var m = CPWorkspaceDirectoryValue(); switch try v.validated() { case .root: m.kind = .root; case let .relative(p): m.kind = .relative; m.relativePath = p.string }; return m }
    public static func decode(_ m: CPWorkspaceDirectoryValue) throws -> WorkspaceDirectory { try unknown(m.unknownFields.data, "workspace_directory"); switch m.kind { case .root: guard !m.hasRelativePath else { throw invalid("workspace_directory") }; return .root; case .relative: guard m.hasRelativePath, let p = try? RelativePath(m.relativePath) else { throw invalid("workspace_directory") }; return .relative(p); default: throw invalid("workspace_directory") } }
    public static func encode(_ v: FileTreeEntryIdentity) throws -> CPFileTreeEntryIdentityValue { var m = CPFileTreeEntryIdentityValue(); m.environmentID = v.environmentID.description; m.relativePath = v.path.string; return m }
    public static func decode(_ m: CPFileTreeEntryIdentityValue) throws -> FileTreeEntryIdentity { try unknown(m.unknownFields.data, "file_tree_entry_identity"); do { return try .init(validating: id(m.environmentID, "environment_id"), path: RelativePath(m.relativePath)) } catch let e as ProtocolMappingError { throw e } catch { throw invalid("file_tree_entry_identity") } }
    public static func encode(_ v: FileTreeEntry) throws -> CPFileTreeEntryValue { var m = CPFileTreeEntryValue(); m.identity = try encode(v.identity); switch v.kind { case .file: m.kind = .file; case .directory: m.kind = .directory; case .symbolicLink: m.kind = .symbolicLink }; return m }
    public static func decode(_ m: CPFileTreeEntryValue) throws -> FileTreeEntry { try unknown(m.unknownFields.data, "file_tree_entry"); guard m.hasIdentity else { throw invalid("file_tree_entry") }; let k: FileTreeEntryKind; switch m.kind { case .file: k = .file; case .directory: k = .directory; case .symbolicLink: k = .symbolicLink; default: throw invalid("file_tree_entry") }; do { return try .init(validating: decode(m.identity), kind: k) } catch let e as ProtocolMappingError { throw e } catch { throw invalid("file_tree_entry") } }
    public static func encode(_ v: FileTreeMutation) throws -> CPFileTreeMutationValue { var m = CPFileTreeMutationValue(); switch v { case let .insert(e): m.insert = try encode(e); case let .remove(i): m.remove = try encode(i); case let .update(e): m.update = try encode(e) }; return m }
    public static func decode(_ m: CPFileTreeMutationValue) throws -> FileTreeMutation { try unknown(m.unknownFields.data, "file_tree_mutation"); switch m.mutation { case let .insert(e): return .insert(try decode(e)); case let .remove(i): return .remove(try decode(i)); case let .update(e): return .update(try decode(e)); case nil: throw invalid("file_tree_mutation") } }
    public static func encode(_ v: FileTreeSnapshot) throws -> CPFileTreeSnapshotValue { guard v.generation > 0, v.generation <= documentJavaScriptMaximum, v.revision <= documentJavaScriptMaximum else { throw invalid("file_tree_snapshot") }; var m = CPFileTreeSnapshotValue(); m.environmentID = v.environmentID.description; m.directory = try encode(v.directory); m.generation = v.generation; m.revision = v.revision; m.children = try v.children.map(encode); return m }
    public static func decode(_ m: CPFileTreeSnapshotValue) throws -> FileTreeSnapshot { try unknown(m.unknownFields.data, "file_tree_snapshot"); guard m.hasDirectory, m.generation > 0, m.generation <= documentJavaScriptMaximum, m.revision <= documentJavaScriptMaximum else { throw invalid("file_tree_snapshot") }; do { return try .init(validating: id(m.environmentID, "environment_id"), directory: decode(m.directory), generation: m.generation, revision: m.revision, children: try m.children.map(decode)) } catch let e as ProtocolMappingError { throw e } catch { throw invalid("file_tree_snapshot") } }
    public static func encode(_ v: FileTreeDelta) throws -> CPFileTreeDeltaValue { guard v.revision > 0, v.revision <= documentJavaScriptMaximum else { throw invalid("file_tree_delta") }; var m = CPFileTreeDeltaValue(); m.environmentID = v.environmentID.description; m.directory = try encode(v.directory); m.revision = v.revision; m.mutations = try v.mutations.map(encode); return m }
    public static func decode(_ m: CPFileTreeDeltaValue) throws -> FileTreeDelta { try unknown(m.unknownFields.data, "file_tree_delta"); guard m.hasDirectory, m.revision > 0, m.revision <= documentJavaScriptMaximum else { throw invalid("file_tree_delta") }; do { return try .init(validating: id(m.environmentID, "environment_id"), directory: decode(m.directory), revision: m.revision, mutations: try m.mutations.map(decode)) } catch let e as ProtocolMappingError { throw e } catch { throw invalid("file_tree_delta") } }

    public static func decodeControlEnvelope(_ data: Data) throws -> CPHostDataPlaneControlEnvelope { let m: CPHostDataPlaneControlEnvelope; do { m = try .init(serializedBytes: data) } catch { throw invalid("host_data_plane_control_envelope") }; try validate(m); return m }
    public static func decodeHandshakeResponse(_ data: Data) throws -> CPHandshakeResponse { let m = try decodeControlEnvelope(data); guard case let .handshakeResponse(r)? = m.payload else { throw invalid("handshake_response") }; return r }
    public static func decodeDocumentEnvelope(_ data: Data) throws -> CPDocumentEnvelope { let m: CPDocumentEnvelope; do { m = try .init(serializedBytes: data) } catch { throw invalid("document_envelope") }; try validate(m); return m }
    public static func decodeFileTreeEnvelope(_ data: Data) throws -> CPFileTreeEnvelope { let m: CPFileTreeEnvelope; do { m = try .init(serializedBytes: data) } catch { throw invalid("file_tree_envelope") }; try validate(m); return m }
    public static func decodeEnvelope(_ frame: Frame) throws -> HostDataPlaneDecodedEnvelope { guard frame.header.flags == 0 else { throw invalid("host_data_plane_flags") }; switch frame.header.channel { case .control: return .control(try decodeControlEnvelope(frame.payload)); case .documentEdits: return .document(try decodeDocumentEnvelope(frame.payload)); case .fileTreeEvents: return .fileTree(try decodeFileTreeEnvelope(frame.payload)); default: throw invalid("host_data_plane_channel") } }

    private static func validate(_ m: CPHostDataPlaneControlEnvelope) throws { try unknown(m.unknownFields.data, "host_data_plane_control_envelope"); guard let p = m.payload else { throw invalid("host_data_plane_control_envelope") }; switch p { case let .handshakeRequest(x): try unknown(x.unknownFields.data, "handshake_request"); guard x.protocolMajor == 1, x.protocolMinor == 1, (try? id(x.deviceID, "device_id") as DeviceID) != nil, x.requestedFeatures == [ProtocolFeature.hostDataPlane.rawValue] else { throw invalid("handshake_request") }; case let .handshakeResponse(x): try unknown(x.unknownFields.data, "handshake_response"); guard x.protocolMajor == 1, x.protocolMinor == 1, (try? id(x.connectionID, "connection_id") as ConnectionID) != nil, x.acceptedFeatures == [ProtocolFeature.hostDataPlane.rawValue], x.serviceKind == "host-data-plane" else { throw invalid("handshake_response") }; case let .authenticate(x): try unknown(x.unknownFields.data, "host_data_plane_authenticate"); guard !x.ticket.isEmpty, x.hasBinding else { throw invalid("host_data_plane_authenticate") }; _ = try decode(x.binding); case let .authenticated(x): try unknown(x.unknownFields.data, "host_data_plane_authenticated"); guard x.hasBinding else { throw invalid("host_data_plane_authenticated") }; _ = try decode(x.binding); case let .error(x): try error(x) } }
    private static func validate(_ m: CPDocumentEnvelope) throws { try unknown(m.unknownFields.data, "document_envelope"); _ = try request(m.requestID); guard m.hasBinding, let p = m.payload else { throw invalid("document_envelope") }; let b = try decode(m.binding); switch p { case let .openRequest(x): try unknown(x.unknownFields.data, "document_open_request"); guard (try? RelativePath(x.relativePath)) != nil else { throw invalid("document_open_request") }; case let .snapshotRequest(x): try documentRequest(x.unknownFields.data, x.documentID, "document_snapshot_request"); case let .acquireLeaseRequest(x): try documentRequest(x.unknownFields.data, x.documentID, "document_acquire_lease_request"); case let .transferLeaseRequest(x): try unknown(x.unknownFields.data, "document_transfer_lease_request"); _ = try id(x.documentID, "document_id") as DocumentID; _ = try id(x.fromEditLeaseID, "edit_lease_id") as EditLeaseID; _ = try id(x.targetClientInstanceID, "client_instance_id") as ClientInstanceID; case let .applyRequest(x): _ = try decode(x); case let .flushRequest(x): try documentRequest(x.unknownFields.data, x.documentID, "document_flush_request"); guard x.throughClientSequence <= documentJavaScriptMaximum else { throw invalid("document_flush_request") }; case let .saveRequest(x): try unknown(x.unknownFields.data, "document_save_request"); _ = try id(x.documentID, "document_id") as DocumentID; guard x.hasExpectedFingerprint else { throw invalid("document_save_request") }; _ = try decode(x.expectedFingerprint); case let .discardRequest(x): try documentRequest(x.unknownFields.data, x.documentID, "document_discard_request"); case let .snapshotResult(x): guard try decode(x).environmentID == b.environmentID else { throw invalid("document_snapshot") }; case let .leaseResult(x): _ = try decode(x); case let .acknowledgementResult(x): _ = try decode(x); case let .flushResult(x): try unknown(x.unknownFields.data, "document_flush_result"); guard x.documentVersion <= documentJavaScriptMaximum else { throw invalid("document_flush_result") }; case let .error(x): try error(x) } }
    private static func validate(_ m: CPFileTreeEnvelope) throws { try unknown(m.unknownFields.data, "file_tree_envelope"); let requestID = try request(m.requestID); guard m.hasBinding, let p = m.payload else { throw invalid("file_tree_envelope") }; let b = try decode(m.binding); switch p { case let .childrenRequest(x): try unknown(x.unknownFields.data, "file_tree_children_request"); guard x.hasDirectory else { throw invalid("file_tree_children_request") }; _ = try decode(x.directory); case let .subscribeRequest(x): try unknown(x.unknownFields.data, "file_tree_subscribe_request"); guard x.afterRevision <= documentJavaScriptMaximum else { throw invalid("file_tree_subscribe_request") }; case let .deltaAck(x): try ack(x.unknownFields.data, x.subscriptionID, x.eventID, x.revision, "file_tree_delta_ack"); case let .cancelRequest(x): try unknown(x.unknownFields.data, "file_tree_cancel_request"); _ = try request(x.subscriptionID); case let .snapshotResult(x): let snapshot = try decode(x); guard snapshot.environmentID == b.environmentID, snapshot.generation == b.activeContextGeneration else { throw invalid("file_tree_snapshot") }; case let .subscriptionAccepted(x): try unknown(x.unknownFields.data, "file_tree_subscription_accepted"); guard try request(x.subscriptionID) == requestID, x.revision <= documentJavaScriptMaximum else { throw invalid("file_tree_subscription_accepted") }; case let .deltaEvent(x): try unknown(x.unknownFields.data, "file_tree_delta_event"); _ = try request(x.subscriptionID); guard try request(x.eventID) == requestID, x.hasDelta, try decode(x.delta).environmentID == b.environmentID else { throw invalid("file_tree_delta") }; case let .ackAccepted(x): try ack(x.unknownFields.data, x.subscriptionID, x.eventID, x.revision, "file_tree_ack_accepted"); case let .cancelled(x): try unknown(x.unknownFields.data, "file_tree_cancelled"); _ = try request(x.subscriptionID); case let .error(x): try error(x) } }
    private static func error(_ x: CPDataPlaneError) throws { try unknown(x.unknownFields.data, "data_plane_error"); guard x.code != .unspecified else { throw invalid("data_plane_error") }; if case .UNRECOGNIZED = x.code { throw invalid("data_plane_error") }; let pair: Bool; switch x.code { case .generationMismatch, .documentBaseVersionMismatch, .documentSequenceGap, .treeRevisionUnavailable: pair = true; default: pair = false }; guard x.hasExpected == pair, x.hasActual == pair, !pair || (x.expected <= documentJavaScriptMaximum && x.actual <= documentJavaScriptMaximum), x.hasCommittedAcknowledgement == (x.code == .documentRecoveryRequired) else { throw invalid("data_plane_error") }; if x.hasCommittedAcknowledgement { _ = try decode(x.committedAcknowledgement) } }
    private static func context(_ v: WorkspaceContextID) -> CPWorkspaceContextID { var m = CPWorkspaceContextID(); switch v { case let .project(id): m.projectID = id.description; case let .conversation(id): m.conversationID = id.description }; return m }
    private static func context(_ m: CPWorkspaceContextID) throws -> WorkspaceContextID { try unknown(m.unknownFields.data, "workspace_context_id"); switch m.kind { case let .projectID(v): return .project(try id(v, "project_id")); case let .conversationID(v): return .conversation(try id(v, "conversation_id")); case nil: throw invalid("host_data_plane_binding") } }
    private static func dirty(_ v: DocumentDirtyState) -> CPDocumentDirtyStateValue { switch v { case .clean: return .clean; case .dirty: return .dirty; case .conflict: return .conflict; case .missing: return .missing } }
    private static func dirty(_ v: CPDocumentDirtyStateValue) throws -> DocumentDirtyState { switch v { case .clean: return .clean; case .dirty: return .dirty; case .conflict: return .conflict; case .missing: return .missing; default: throw invalid("document_snapshot.dirty_state") } }
    private static func maintenance(_ v: DocumentMaintenanceState) -> CPDocumentMaintenanceStateValue { switch v { case .truncatedRecoveryTail: return .truncatedRecoveryTail; case .corruptRecoveryRecord: return .corruptRecoveryRecord; case .compactionDeferred: return .compactionDeferred } }
    private static func maintenance(_ v: CPDocumentMaintenanceStateValue) throws -> DocumentMaintenanceState { switch v { case .truncatedRecoveryTail: return .truncatedRecoveryTail; case .corruptRecoveryRecord: return .corruptRecoveryRecord; case .compactionDeferred: return .compactionDeferred; default: throw invalid("document_snapshot.maintenance") } }
    private static func documentRequest(_ u: Data, _ v: String, _ f: String) throws { try unknown(u, f); _ = try id(v, "document_id") as DocumentID }
    private static func ack(_ u: Data, _ s: String, _ e: String, _ r: UInt64, _ f: String) throws { try unknown(u, f); _ = try request(s); _ = try request(e); guard r > 0, r <= documentJavaScriptMaximum else { throw invalid(f) } }
    private static func request(_ v: String) throws -> RequestID { try id(v, "request_id") }
    private static func id<Scope>(_ v: String, _ field: String) throws -> CockpitID<Scope> { guard let uuid = UUID(uuidString: v) else { throw ProtocolMappingError.invalidIdentifier(field) }; let result = CockpitID<Scope>(uuid); guard result.description == v else { throw ProtocolMappingError.invalidIdentifier(field) }; return result }
    private static func unknown(_ data: Data, _ field: String) throws { try rejectUnknownFields(data, field: field) }
    private static func invalid(_ field: String) -> ProtocolMappingError { .invalidValue(field) }
}
